Repository AY2223S2-CS2113-T14-2/tp, pull requests merged in 2023-03, with the labels that each got.

#22 Add, delete, pack and unpack
  src/main/java/bagpacker/BagPacker.java
  src/main/java/bagpacker/commands/AddCommand.java
  src/main/java/bagpacker/commands/Command.java
  src/main/java/bagpacker/commands/DeleteCommand.java
  src/main/java/bagpacker/commands/HelpCommand.java
  src/main/java/bagpacker/commands/ListCommand.java
  src/main/java/bagpacker/commands/PackCommand.java
  src/main/java/bagpacker/commands/UnpackCommand.java
  src/main/java/bagpacker/iohandler/Parser.java
  src/main/java/bagpacker/packingfunc/Item.java
  src/main/java/bagpacker/packingfunc/PackingList.java
Labels: priority.High, severity.High, type.Story

#38 Add Pack Command Assertion
  src/main/java/bagpacker/commands/PackCommand.java
  src/main/java/bagpacker/iohandler/Parser.java
Labels: priority.High, priority.Medium, severity.Low

#40 Add JUnit tests for addCommand
  src/test/java/bagpacker/BagPackerTest.java
  src/test/java/bagpacker/packingfunctest/CommandsTest.java
Labels: priority.High, type.Enhancement
